### ISSUE TITLE
Decide what to do with the dataset

### ISSUE THREAD

**Issue by rpryzant** [rpryzant/japanese_corpus#10]
## paper options

* **paper option: domain adaptation**
  * Train a model on ASPEC and look at BLEU for aspec and our corpus
  * Train a model on our corpus and look at test BLEU for both
  * Train a model on the combined corpora and look at test BLEU for both
  * teach model to adapt to noisy inputs, i.e. adding some kind of discriminator on top of the standard NMT model that predicts which corpus an example comes from - That should result in the model being able to adapt to different inputs
* **paper option: noisy data adaption: learn to downweigh/upweight examples**
  * manually label a few examples as good/bad
  * add a discrimantor to the model that predicts how likely an example is to be clean and correct
  * scale the gradients by that probability, resulting in noisy examples to be downweighted during training
* **paper option: better alignments**
  * start with a few alignments that we know are good, algin a few sentences, re-train the aligner, and keep repeating that process
* **paper option: linguistic insights**
  * show that there's linguistic phenomina in our new corpus (i.e. casual language) that makes it better for certain sub-tasks
* **paper option: iterative pruning**
  * you can prune a model up to 80% and recover its performance by retraining the non-pruned weights [[PAPER]](https://arxiv.org/abs/1606.09274)
  * what if you pruned, retrained, reinitialized the pruned weights, put a soft clamp on the other weights,  and trained the pruned weights? What if you iterated on this? 
* **arXiv option: stick with dataset**
  * Just create a dataset paper and put it on arXiv without submitting to any conference

**Comment by rpryzant** [comment]
@dennybritz I'm most excited about domain adaptation & noisy data adaptation, but this is really up to you. What's your call?

**Comment by dennybritz** [comment]
I agree. I think a paper on domain adaptation + a novel dataset has a very good chance to be accepted at a conference like EMNLP. Same for noisy data adaptation, but it requires a bit more work due to the required human labels.

I think we can do the following:

1. See if throwing in the subtitles corpus as additional data helps the ASPEC corpus.
2. Come up with a domain adaptation model (i.e. a discriminator on top of the network) and see if that improves over #1 
3. If time, investigate the noisy data adaptation. This applies to our corpus but also ASPEC. I only briefly glanced at the ASPEC corpus, but a lot of its translations seem to be off as well.

I can definitely handle 1 and maybe 2, need to think about it a bit more. The idea is kind of obvious though so I'm wondering if something like this hasn't been already done.

**Comment by rpryzant** [comment]
Sounds good. We'll need a cleaner dataset in any case, so I'll work on setting that up in the meantime

**Comment by dennybritz** [comment]
Yeah, I agree a cleaner dataset would be good. Ideally a larger one too though ;) I wonder if we can improve recall of the initial dataset somehow so that it doesn't become too small when cleaned aggressively.

**Comment by rpryzant** [comment]
I agree, I think I cleaned to heavily the first time around as well...I threw away more than half our phrases

**Comment by rpryzant** [comment]
Seems like we know what to do.
